"""
Onboarding generator — turn the graph into a "start here" codebase tour.

Solves (2026 problem):
  Developers spend ~58% of their time on program comprehension; onboarding to a
  new codebase averages 6 weeks. The 2026 ideal is "a patient senior developer
  that is partly an AI tool with a tree-sitter parser and a knowledge graph" —
  map the repo, identify the stack, surface entry points, document the why.

`coursift onboard <project>` writes an ONBOARDING.md: detected stack, entry
points (god nodes), key modules, a suggested reading order, and the recorded
decisions behind the code.

100% local, no API.
"""

from collections import Counter
from datetime import datetime
from pathlib import Path

from coursift.graph import load_graph
from coursift.config import CONFIG_DIR

STACK_HINTS = {
    "react": "React", "next": "Next.js", "vue": "Vue", "svelte": "Svelte",
    "express": "Express", "fastapi": "FastAPI", "flask": "Flask", "django": "Django",
    "typer": "Typer (CLI)", "click": "Click (CLI)", "stripe": "Stripe",
    "supabase": "Supabase", "sanity": "Sanity CMS", "anthropic": "Anthropic SDK",
    "openai": "OpenAI SDK", "sqlalchemy": "SQLAlchemy", "prisma": "Prisma",
    "tailwindcss": "Tailwind CSS", "pytest": "pytest", "networkx": "NetworkX",
}


def generate_onboarding(project_name: str) -> str:
    graph = load_graph()
    if not graph:
        return "# Onboarding\n\n_No graph. Run `coursift build` first._\n"

    nodes = [n for n in graph.get("nodes", []) if n.get("project", "").lower() == project_name.lower()]
    if not nodes:
        avail = sorted({n.get("project", "") for n in graph.get("nodes", [])})
        return f"# Onboarding\n\nProject '{project_name}' not found. Available: {', '.join(avail)}\n"

    files = [n for n in nodes if n.get("kind") == "file"]
    functions = [n for n in nodes if n.get("kind") == "function"]
    classes = [n for n in nodes if n.get("kind") == "class"]
    imports = [n for n in nodes if n.get("kind") == "import"]
    god_nodes = [n for n in nodes if n.get("god_node")]
    sessions = [n for n in graph.get("nodes", [])
                if n.get("kind") == "session" and n.get("project", "").lower() == project_name.lower()]

    # detect stack from imports
    detected = []
    import_labels = {i.get("label", "").lower() for i in imports}
    for hint, name in STACK_HINTS.items():
        if any(hint in lbl for lbl in import_labels):
            detected.append(name)

    # key modules = files with the most defined symbols
    file_symbol_count: Counter = Counter()
    for fn in functions + classes:
        file_symbol_count[Path(fn.get("file", "")).name] += 1

    lines = [
        f"# Onboarding — {project_name}",
        f"\n> Auto-generated by Coursift · {datetime.now().strftime('%Y-%m-%d')} · "
        f"{len(files)} files · {len(functions)} functions · {len(classes)} classes",
        "",
        "## 1. Tech stack (detected)",
        "",
        ("- " + "\n- ".join(sorted(set(detected)))) if detected else "_Not auto-detected._",
        "",
        "## 2. Entry points (most-connected — start here)",
        "",
    ]
    if god_nodes:
        for n in god_nodes[:8]:
            lines.append(f"- **{n['label']}** [dim]`{Path(n.get('file','')).name}`[/dim]")
    else:
        for fname, count in file_symbol_count.most_common(8):
            lines.append(f"- **{fname}** — {count} symbols")

    lines += ["", "## 3. Key modules (by symbol density)", ""]
    for fname, count in file_symbol_count.most_common(10):
        lines.append(f"- `{fname}` — {count} functions/classes")

    lines += ["", "## 4. Suggested reading order", ""]
    order = [f for f, _ in file_symbol_count.most_common(6)]
    for i, fname in enumerate(order, 1):
        lines.append(f"{i}. `{fname}`")

    # decisions = the "why"
    decisions = []
    for s in sessions:
        decisions.extend(s.get("decisions", [])[:4])
    if decisions:
        lines += ["", "## 5. Why it's built this way (recorded decisions)", ""]
        for d in list(dict.fromkeys(decisions))[:8]:
            lines.append(f"- {d}")

    lines += [
        "",
        "## 6. Next steps",
        "- Run `coursift search \"<topic>\"` to find code by meaning.",
        "- Run `coursift impact <symbol>` before changing anything central.",
        "- Run `coursift lessons` to see what has failed here before.",
        "",
    ]
    # strip rich markup we accidentally added
    return "\n".join(lines).replace("[dim]", "").replace("[/dim]", "")


def write_onboarding(project_name: str) -> Path:
    content = generate_onboarding(project_name)
    path = CONFIG_DIR / f"ONBOARDING_{project_name}.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return path
